### ISSUE TITLE
Where to find translations of mac-font-features

### ISSUE THREAD

**Issue by milotype** [fontforge/fontforge#3857]
I don't know where the existing translations come from!? (see attachement)
File > Preferences > Mac > Features

I'd like to translate those into croatian and german (which is partialy translated).
Can someone please let me know, where to find the appropriate file(s).

![Mac-features](https://user-images.githubusercontent.com/43657314/62477683-c1c85b00-b7a9-11e9-99de-f23563bfd769.png)

**Comment by skef** [comment]
This is probably not a particularly helpful answer but those strings are in a table in [fontforge/macenc.c](https://github.com/fontforge/fontforge/blob/a263e0dc1f813894f7405658ab0c22d871b9080c/fontforge/macenc.c#L1466)

**Comment by milotype** [comment]
Actually it does help!
I'll simply translate all "english" strings, code 0, for instance:
`{ &fs_names[146], 0, 0, "All Typographic Features" }`
into croatian, with the appropriate code 18:
`{ &fs_names[146], 0, 18, "Sve tipografske funkcije" }`
and add the whole croatian list into the file at the appropirate place.

QUESTION:
How do I "encode" croatian diacritics? I guess UTF-8 shouldn't be used in that file.
ć, č, š, ž, Ć, Č, Đ, Š, Ž

I've notice in German for instance: Br\237che (=Brüche)
(couldn't figure out what encoding uses `/237` for 'LATIN SMALL LETTER U WITH DIAERESIS')

**Comment by skef** [comment]
This stuff is *really* old and looks like it was built up by hand -- I'm not sure just adding to the first table will work but it might. 

It appears the text is encoded as [Mac OS Roman](https://en.wikipedia.org/wiki/Mac_OS_Roman)

**Comment by skef** [comment]
So I guess that means you should either use [Mac OS Croatian](https://en.wikipedia.org/wiki/Mac_OS_Croatian_encoding) or there's nothing likely to work without some more modification.

**Comment by milotype** [comment]
I've produced a `.pot` file for the AAT-font-features. (see attachment)

Actually there are 146 "english" AAT-strings, but some are duplicates (which isn't allowed in `.pot` files, so in the end, there are 136 AAT-strings to translate. HOWEVER, I've put a comment for the strings which have duplicates, indicating the order number of the "feature". For instance:

```
#: ../fontforge/macenc.c:108
#. duplicate 108, 133, 136, 139, 142
msgid "Proportional"
msgstr ""
```
where the numbers in the comment specify the order as it is in the "fontforge/macenc.c" file.

If you think this could be usefull, please do use it in any way you find appropriate. Please check the header of the file and change it, if needed. I'm sending it as a .zip file, because .pot extension isn't supported by github. If you think I should send it as a "bug-report", please let me know.

In the mean time I'll do the translation on the "fontforge/macenc.c" file as it is now and send a PR.

[FF-AAT.pot.zip](https://github.com/fontforge/fontforge/files/3469044/FF-AAT.pot.zip)

**Comment by milotype** [comment]
I still don't understand the "encoding" in the "fontforge/macenc.c" file.
For instance, why is the German lower-case-u-umlaut specified as:
`Br\237che (=Brüche)`
Whatever I've checked, I simply don't get "237" as any sort of code for that character!??
Character | Macintosh Number | Unicode Number | Macintosh Hex | Unicode Hex | HTML 4.0 Entity | Unicode Name | Unicode Range
-- | -- | -- | -- | -- | -- | -- | --
ü | 159 | 252 | 0x9F | U+00FC | &uuml; | Latin small letter u with diaeresis | Latin-1 Supplement

So how would I "code" the croatian characters: ć, č, š, ž, Ć, Č, Đ, Š, Ž?
What am I missing out?

**Comment by skef** [comment]
In C strings a backslash followed by three 0-7 digits is in octal. 237 in octal is 9F in hexidecimal, and therefore matches that "Macintosh Hex" value. So to encode the same way you'll need to grab the hex values from that Mac OS Croatian link above and covert them to octal. (Hex encoding could work but there's no limit to the length of a hex number, which makes them pickier to work with.)

**Comment by milotype** [comment]
Before I do a PR, can you please check if my additions for the croatian are any good?
I don't know where to place the "macenc.c" on my mac 10.11.6, in order to test it.

As I don't know if the "fs_names"-number has any significance, I've placed the croatian strings in the range of 601-746. Or should it be "NULL", like in dutch?
` { &fs_names[601], 0, 18, "Sve tipografske funkcije" },`
...
`{ &fs_names[746], 0, 18, "Kanoni\415ko rastavljanje" },`

[macenc.c.txt](https://github.com/fontforge/fontforge/files/3469997/macenc.c.txt)

**Comment by skef** [comment]
That's a source file, so it needs to be compiled in. 

I'm willing to give it a shot on my (Arch Linux) system, but I've never done much with I18N and L10N.

**Comment by milotype** [comment]
@skef When you're done, please let me know. I'd send a PR, because I made some corrections on the translation.

**Comment by ctrlcctrlv** [comment]
(Technically there's no length to an octal number either, the C standard simply imposes one.)

**Comment by skef** [comment]
First off, that file wasn't encoded correctly. This is at least better and I think it's correct: 

[macenc.c.txt](https://github.com/fontforge/fontforge/files/3490166/macenc.c.txt)

(You were converting the Unicode values to octal rather than the Mac Roman values. You were supposed to use the table-top and left hex values as a starting point. You also didn't attend to what strings needed capitals.) 

Second, I compiled this in, built, and switched to a hr_HR.utf8 locale, which made the usual strings in FontForge change. I went to the "Mac" preferences section and the strings were still in English. 

I don't know what these translations are for or how they are intended to be used. Given that these are in a weird encoding that FontForge doesn't know about it's quite likely they're not intended for display but some other purpose. Maybe for dumping into a mac format font. It's beyond my scope as a reviewer/helper here to determine that.

**Comment by skef** [comment]
> (Technically there's no length limit to an octal number either, the C standard simply imposes one.)

Well, yes and no. It's true that there's no length limit on octal *representations* of numbers. But the role of string literals in C is to encode a sequence that can be validly pointed to by a `char`, and therefore on a one byte boundary. Octal representations don't fall on an eight-bit boundary, leaving the interpretation of "\501" unclear. Enforcing a one-escape/one `char` convention for octal is a clear convention that avoids boundary confusion.

**Comment by milotype** [comment]
Thank you for your answers. A bit too complicated for me when it comes to all that encoding stuff.

Yes I've noticed myself, that I've missed some capital letters. I've corrected them in my file.

I use only `export LANG=hr.UTF-8` (but I doubt hr_HR makes a difference).

I do think the file is intended for displaying in FontForge, as it does work for french, dutch and german. So it would be cool if someone would find a solution for the croatian language.

I'm attaching my corrected file. The codes for the croatian accented characters are wrong as before (with corrected capitals and some other translation corrections), but the file should be encoded MacRoman now. (I just added the .txt suffix, so I could upload the file here).
[macenc.c.txt](https://github.com/fontforge/fontforge/files/3490347/macenc.c.txt)

If someone can tell me the exact codes for the following croatian accented characters, I'd update the file myself:
ć = 
č = 
đ = 
š = 
ž = 
Ć = 
Č = 
Đ = 
Š = 
Ž =

**Comment by skef** [comment]
Before I go on, I've looked at this a bit more and I'm still not sure what the point of this file is. If it's a pre-unicode-support attempt to support multiple character sets, it would be best to just translate everything into unicode and be done with it. But assuming the file should be kept as it is...

Rather than answer your whole question, here is a procedure using č as an example:

1. Go to https://en.wikipedia.org/wiki/Mac_OS_Croatian_encoding
2. Find č. The thicker boxes are around the characters of most interest. It's there with its unicode hex value below it in the second-from-the-bottom row. 
3. Note the Hex value in the leftmost column and that in the topmost column: E_ + _8 -> E8
4. Translate that to octal: \350 That's the code. 

Note that 35 in octal is 29 in decimal. The Croatian mapping array `croatian` starts on line 129 of `macenc.c`. The 30th row starts with `0x010d`, which is the Unicode value back. So that array is more or less the table at https://en.wikipedia.org/wiki/Mac_OS_Croatian_encoding except with 8 entries per line rather than 16.  `MacEncLangToTable()` on line 1103 maps 18 to that `croatian` array.  That's how "all this works". 

For testing, if you tell me where and how you manage to get FontForge to display the French versions I might have better luck testing the Croatian versions. When I wrote:

>  but I've never done much with I18N and L10N.

I was prompting for instructions on how to test your code.

**Comment by milotype** [comment]
Try it with `export LANG=fr.UTF-8`, as french seem pretty much translated.
Go to: **Element > Font Info > Mac Features**
- then hit "Default" in the bottom right of that window
- double click any of the displayed features
- another "Feature" window pops up with more settings (not everything is translated in the different languages, such as de, fr, it, nl)

In the mean time I'll try to get the croatian codes.

**Comment by skef** [comment]
Hmm -- no, the new strings are not appearing there. Some additional "piece" must be missing.

**Comment by milotype** [comment]
What do you mean with "new strings are not appearing there"?

The croatian should be correct now ...
[macenc.c.txt](https://github.com/fontforge/fontforge/files/3490484/macenc.c.txt)

**Comment by skef** [comment]
Oh good grief. 

Here's the deal, and what you have to do. The `fs_names` array starts on line 1467:

```static struct macname fs_names[] = {
        { &fs_names[146], 0, 0, "All Typographic Features" },
        { &fs_names[147], 0, 0, "All Type Features" },
        { &fs_names[148], 0, 0, "Ligatures" },
        { &fs_names[149], 0, 0, "Required Ligatures" },
```
Note the first sub-element, which is an offset into this very array. Entry 146 will be on line 1467+146 (because entries start at zero) 1613. Here are the lines starting from 1610:
```
        { &fs_names[286], 0, 0, "Full-Width" },
        { &fs_names[287], 0, 0, "Unicode Decomposition" },
        { &fs_names[288], 0, 0, "Canonical Decomposition" },
        { &fs_names[289], 0, 1, "Fonctions typographiques" },
        { &fs_names[290], 0, 1, "Toutes fonctions typographiques" },
        { &fs_names[291], 0, 1, "Ligatures" },
        { &fs_names[397], 0, 1, "Ligatures Requises" },
```
Note that 1613 is the first French line. And that's the translation of "All Typographic Features". So what we have here is a linked list of sorts! Each message links to its next equivalent in another language. The list is terminated with a `NULL` in the initial sub-element. 

Therefore, what you need to do is:

1. Put `NULL` as the first entry in each of your translations (easy)
2. Find the previous entry for each translated statement that has the NULL and link it forward to yours (more difficult!)

**Comment by skef** [comment]
> What do you mean with "new strings are not appearing there"?

I mean with the previous version of your file compiled in the strings don't appear. Presumably for the reason outlined in my previous comment.

**Comment by milotype** [comment]
Just for info, this is what I see when looking at english and french.

![en](https://user-images.githubusercontent.com/43657314/62840106-8e983700-bc95-11e9-8adb-1425a545fe92.png)

![fr](https://user-images.githubusercontent.com/43657314/62840107-92c45480-bc95-11e9-8a7b-f7309fb5ac56.png)

**Comment by skef** [comment]
Yes, I see those, I just don't see your new strings.

**Comment by milotype** [comment]
Thank you again for all your help.

I know croatian isn't the most essential language, but if someone can find a solution, that would be great. And probably it is needed for other localizations beyond the scope of mac roman encoding ...

**Comment by skef** [comment]
We're quite close -- you just need to do a bit of bookkeeping. Do you understand my longer recent message at least a little?

**Comment by milotype** [comment]
Sorry, I just realized I've missed that one out.
Yes, 1st point is easy.
Point 2 ????? Whaaat? Can you give me one example on my latest file, please.

**Comment by skef** [comment]
Remember that the table starts on line 1467, which is the "zero" entry. 

* Line 1467:  `{ &fs_names[146], 0, 0, "All Typographic Features" },`
* Line 1467+146=1613: `{ &fs_names[289], 0, 1, "Fonctions typographiques" },`
* Line 1467+289=1756: `{ &fs_names[342], 0, 2, "Alle typografischen M\232glichkeiten" },`
* Line 1467+342=1809: `{ &fs_names[394], 0, 3, "Funzioni Tipografiche" },`
* Line 1467+394=1861: `{ NULL, 0, 4, "Alle typografische kenmerken" },`

Now, in the last version of the file I looked at, your translation is on line 2007: `{ &fs_names[601], 0, 18, "Sve tipografske funkcije" },`. That first entry needs to become `NULL`, like in line 1861. Then the first entry in 1861 needs to point to yours. 2001-1467 = 540. So that line would become { &fs_names[540], 0, 4, "Alle typografische kenmerken" },`

Get the idea?

**Comment by skef** [comment]
It might be easier to temporarily copy the table out to a file on its own but without the first line, so that entry 1 is on line 1, entry 2 is on line 2, etc. Line 1467 is "entry 0" because C-arrays are indexed from zero.

**Comment by milotype** [comment]
I am already working with a spreadsheet for the croatian ;-)

I've changed all croatian to "NULL".

Basically I need to change the whole dutch lines?
And if a croatian line doesn't exist in dutch, I have to go to the next language where that specific line exists? I think the italian section isn't complete (there are some "NULL" lines, and they don't show in FontForge).

I'll build the whole stuff tomorrow as spreadsheets ...

**Comment by skef** [comment]
Yes, that's the idea. That forward mapping is how the code tracks which messages are equivalent.

If I were tasked with this I would probably start with a script, but that wouldn't address the "initial" mapping. However, a spreadsheet is a good tool for tackling this -- maybe a preferable one. 

It's of primary importance that each chain of translations winds up "NULL terminated". Otherwise FontForge is likely to crash.

**Comment by milotype** [comment]
I guess you are refering to the line:
`	{ NULL, 0, 0, NULL }`
as it is now.

**Comment by skef** [comment]
That's true, but it's just as important that every "chain" of translations ends with an entry with NULL as the first sub-element. Otherwise FontForge will interpret that first entry as the offset into the table for the next translation, and since it won't be one "all hell will break loose".

**Comment by skef** [comment]
(BTW that "oh good grief" above was directed towards a certain GW, not you ... )

**Comment by ctrlcctrlv** [comment]
GW did it this way for a reason, FYI. See this [email from him](https://sourceforge.net/p/pfaedit/mailman/message/3027401/) sent in 2003.

**Comment by skef** [comment]
> "This works differently from the normal ui stuff because all languages
need to be available for everyone (rather than just one language at a
time)."

Unfortunately that doesn't account for the choice of mac-specific encoding. A great way to have "all languages available for everyone" is to have all strings encoded as Unicode. Why have them in this weird mac encoding and then re-encode them? Was 2003 just too early for that?

**Comment by milotype** [comment]
@skef
> That's true, but it's just as important that every "chain" of translations ends with an entry with NULL as the first sub-element. ...

I'm not sure with that NULL between translations - in the original file, the languages are not separated.

Attached is my new file - I hope everything is fine like that, and that I understood your instructions correctly. Keeping my fingers crossed ...
[macenc.c12.txt](https://github.com/fontforge/fontforge/files/3493449/macenc.c12.txt)

**Comment by skef** [comment]
*None* of those octal values were correct, not even the one I used in my example. (Why would you still use \415 for č?) You also didn't terminate the strings for the previous translation. But never mind, here is a working version:

[macenc.c13.txt](https://github.com/fontforge/fontforge/files/3493750/macenc.c13.txt)

I can confirm the strings that show up in the preferences interface (which seem to be a subset of the full list) now have Croatian entries. So the list mapping seems to be correct, which is a good thing.

**Comment by milotype** [comment]
OMG, sorry! I've written down all the correct octal values, but completely forgot to exchange them in my spreadsheet ...

**Comment by skef** [comment]
Well that's OK it's software -- it happens.

**Comment by milotype** [comment]
In the mean time, I'm also working on a "new" file, where every language will have 146 lines, so this ridiculous calculation of individual lines wouldn't be necessary. I'm taking all existing translations as they are (plus translating some more german stuff). So the file would have: en, fr, de, it, nl, hr.

The idea is, that whatever line isn't translated, there will be the original english text. So later, if someone wants to transalte missing strings in those languages, only the english text in that line will have to be changed, nothing else. Until now, the english is being displayed anyway, when something isn't translated (and this file isn't a "real" translation file). Adding other languages than those six, would mean to simply add a whole block of 146 lines ...

Take a look at the PDF. I hope you get the idea what I've thought of building ...
[macenc.c20.pdf](https://github.com/fontforge/fontforge/files/3493970/macenc.c20.pdf)

Let me know what you think of it?

**Comment by milotype** [comment]
> Well that's OK it's software -- it happens.

No, this time it was me, multitasking ... which obviously I'm not capable of ;-)

**Comment by skef** [comment]
I appreciate the effort to fix the file but that change would make it harder to review reliably. I would say that the file should either be completely overhauled or left with the current pattern in place.

**Comment by milotype** [comment]
Well reviewing would actually be much easier, as there would be no counting forward/backward, etc. But I do understand your scepsis.

I suggest we do the following:

1. I'll send a PR with your last file, so everything is the same, plus new croatian translation.
2. I'll open an issue, proposing my solution, and we'll see what happens. I doubt that any translator is going to be able to work with the pattern as it is now. And maybe someone comes up with a better solution.

How about that?

**Comment by skef** [comment]
Sounds good to me!

**Comment by milotype** [comment]
Thank you for all your help!
I think we can close this issue now.
